set_project("ccms")
set_version("0.1.0")
set_languages("c11")

add_rules("mode.debug", "mode.release")

add_rules("plugin.compile_commands.autoupdate", { outputdir = "." })
target("ccms")
  set_default(true)
  -- set_kind("static")
  -- set_basename("ccms-$(mode)-$(os)-$(arch)")
  set_kind("headeronly")
  add_headerfiles("include/(ccms/*.h)")
  add_headerfiles("include/(ccms/arenas/*.h)")
  add_includedirs("include", { public = true })
  -- add_files("src/*.c")
  add_rules("utils.install.cmake_importfiles")
  add_rules("utils.install.pkgconfig_importfiles")

target("examples/main")
  set_enabled(true)
  set_kind("binary")
  add_files("examples/main.c")
  add_deps("ccms")
